// Generated by generate_forwarders.py.
#include "Proxy.h"
using namespace ksword::titan;
extern "C" {
ULONG_PTR GetPEBLocation(HANDLE hProcess) {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().GetPEBLocation(hProcess);
}
ULONG_PTR GetTEBLocation(HANDLE hThread) {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().GetTEBLocation(hThread);
}
bool ReplayGetPosition(TITAN_REPLAY_POSITION* Position) {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().ReplayGetPosition(Position);
}
bool ReplayGetExtent(TITAN_REPLAY_POSITION* First, TITAN_REPLAY_POSITION* Last) {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().ReplayGetExtent(First, Last);
}
bool ReplaySetPosition(const TITAN_REPLAY_POSITION* Position) {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().ReplaySetPosition(Position);
}
bool ReplayRunBack() {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().ReplayRunBack();
}
bool ReplayStepBack(TITANCBSTEP StepCallBack) {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().ReplayStepBack(StepCallBack);
}
bool GetFullContextDataEx(HANDLE hActiveThread, TITAN_ENGINE_CONTEXT_t* titcontext) {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().GetFullContextDataEx(hActiveThread, titcontext);
}
bool SetFullContextDataEx(HANDLE hActiveThread, TITAN_ENGINE_CONTEXT_t* titcontext) {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().SetFullContextDataEx(hActiveThread, titcontext);
}
ULONG_PTR GetContextDataEx(HANDLE hActiveThread, TitanRegister IndexOfRegister) {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().GetContextDataEx(hActiveThread, IndexOfRegister);
}
bool SetContextDataEx(HANDLE hActiveThread, TitanRegister IndexOfRegister, ULONG_PTR NewRegisterValue) {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().SetContextDataEx(hActiveThread, IndexOfRegister, NewRegisterValue);
}
bool GetAVXContext(HANDLE hActiveThread, TITAN_ENGINE_CONTEXT_t* titcontext) {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().GetAVXContext(hActiveThread, titcontext);
}
bool SetAVXContext(HANDLE hActiveThread, TITAN_ENGINE_CONTEXT_t* titcontext) {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().SetAVXContext(hActiveThread, titcontext);
}
bool GetAVX512Context(HANDLE hActiveThread, TITAN_ENGINE_CONTEXT_AVX512_t* titcontext) {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().GetAVX512Context(hActiveThread, titcontext);
}
bool SetAVX512Context(HANDLE hActiveThread, TITAN_ENGINE_CONTEXT_AVX512_t* titcontext) {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().SetAVX512Context(hActiveThread, titcontext);
}
const DEBUG_EVENT* GetDebugData() {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().GetDebugData();
}
void SetCustomHandler(TitanCustomHandler ExceptionId, TITANCALLBACKARG CallBack) {
    if (ensureNative() != ERROR_SUCCESS) { return; }
    activeApi().SetCustomHandler(ExceptionId, CallBack);
}
void SetNextDbgContinueStatus(DWORD SetDbgCode) {
    if (ensureNative() != ERROR_SUCCESS) { return; }
    activeApi().SetNextDbgContinueStatus(SetDbgCode);
}
bool IsFileBeingDebugged() {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().IsFileBeingDebugged();
}
HANDLE TitanOpenProcess(DWORD dwDesiredAccess, bool bInheritHandle, DWORD dwProcessId) {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().TitanOpenProcess(dwDesiredAccess, bInheritHandle, dwProcessId);
}
HANDLE TitanOpenThread(DWORD dwDesiredAccess, bool bInheritHandle, DWORD dwThreadId) {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().TitanOpenThread(dwDesiredAccess, bInheritHandle, dwThreadId);
}
bool TitanGetProcessImagePathW(HANDLE hProcess, LPWSTR szPath, SIZE_T cchPath) {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().TitanGetProcessImagePathW(hProcess, szPath, cchPath);
}
bool TitanGetModulePathW(HANDLE hProcess, ULONG_PTR ModuleBase, LPWSTR szPath, SIZE_T cchPath) {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().TitanGetModulePathW(hProcess, ModuleBase, szPath, cchPath);
}
bool TitanCloseHandle(HANDLE hEngineHandle) {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().TitanCloseHandle(hEngineHandle);
}
bool ProcessIsWow64(HANDLE hProcess, PBOOL isWow64) {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().ProcessIsWow64(hProcess, isWow64);
}
bool RequestPause(TitanPausePolicy MaximumPolicy, TITANCBPAUSE PauseCallback) {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().RequestPause(MaximumPolicy, PauseCallback);
}
HANDLE TitanCreateRemoteThread(HANDLE hProcess, LPTHREAD_START_ROUTINE start, LPVOID argument, DWORD creationFlags, LPDWORD threadId) {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().TitanCreateRemoteThread(hProcess, start, argument, creationFlags, threadId);
}
DWORD TitanGetThreadId(HANDLE hThread) {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().TitanGetThreadId(hThread);
}
int TitanGetThreadPriority(HANDLE hThread) {
    if (ensureNative() != ERROR_SUCCESS) { return THREAD_PRIORITY_ERROR_RETURN; }
    return activeApi().TitanGetThreadPriority(hThread);
}
bool TitanSetThreadPriority(HANDLE hThread, int priority) {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().TitanSetThreadPriority(hThread, priority);
}
bool TitanGetThreadTimes(HANDLE hThread, LPFILETIME creation, LPFILETIME exit, LPFILETIME kernel, LPFILETIME user) {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().TitanGetThreadTimes(hThread, creation, exit, kernel, user);
}
bool TitanQueryThreadCycleTime(HANDLE hThread, PULONG64 cycleTime) {
    if (ensureNative() != ERROR_SUCCESS) { return {}; }
    return activeApi().TitanQueryThreadCycleTime(hThread, cycleTime);
}
}
