"""Generate exact typed canonical wrappers; no handwritten ABI signatures."""
from pathlib import Path
import re

root = Path(__file__).resolve().parent
header = root.parent / 'third_party/x64dbg_abi/TitanEngine.h'
decls = re.findall(r'__declspec\(dllexport\)\s+(.+?)\s+(\w+)\((.*?)\);', header.read_text())
custom = {'InitDebugW', 'StopDebug', 'DetachDebuggerEx', 'TitanTerminateProcess',
          'TitanTerminateThread', 'SetHardwareBreakPoint', 'DeleteHardwareBreakPoint',
          'RemoveAllBreakPoints', 'EngineCheckStructAlignment', 'MemoryFreeSafe', 'DebugLoop', 'AttachDebugger',
          'StepInto', 'StepOver', 'MemoryReadSafe', 'MemoryReadUnsafe',
          'SetBPX', 'DeleteBPX', 'IsBPXEnabled', 'GetUnusedHardwareBreakPointRegister',
          'SetMemoryBPXEx', 'RemoveMemoryBPX', 'MemoryWriteSafe', 'SetBPXOptions'}
api = ['// Generated by generate_forwarders.py. Canonical types are never retyped.',
       '#pragma once', '#pragma warning(push)', '#pragma warning(disable: 4324)',
       '#include "../third_party/x64dbg_abi/TitanEngine.h"', '#pragma warning(pop)',
       'namespace ksword::titan {', 'struct NativeApi {']
api += [f'    decltype(&::{name}) {name} = nullptr;' for _, name, _ in decls]
api += ['};', 'extern NativeApi nativeApi;', 'DWORD ensureNative();', '}']
(root / 'NativeApi.h').write_text('\n'.join(api) + '\n')
resolve = ['// Generated canonical native export validation.']
resolve += [f'KSW_RESOLVE({name});' for _, name, _ in decls]
(root / 'ResolveExports.inc').write_text('\n'.join(resolve) + '\n')
forward = ['// Generated by generate_forwarders.py.', '#include "Proxy.h"',
           'using namespace ksword::titan;', 'extern "C" {']
for ret, name, args in decls:
    if name in custom: continue
    names = [re.search(r'(\w+)\s*$', arg.strip()).group(1) for arg in args.split(',') if arg.strip()]
    fallback = '' if ret == 'void' else ('MAXDWORD' if name in {'TitanSuspendThread', 'TitanResumeThread'} else
                                       'THREAD_PRIORITY_ERROR_RETURN' if name == 'TitanGetThreadPriority' else '{}')
    fail = 'return;' if ret == 'void' else f'return {fallback};'
    call = f'nativeApi.{name}({", ".join(names)})'
    prefix = '' if ret == 'void' else 'return '
    forward += [f'{ret} {name}({args}) {{', f'    if (ensureNative() != ERROR_SUCCESS) {{ {fail} }}',
                f'    {prefix}{call};', '}']
forward += ['}']
(root / 'Forwarders.cpp').write_text('\n'.join(forward) + '\n')
definition = (root.parent / 'third_party/x64dbg_abi/TitanEngine.def').read_text().rstrip() + '\n'
definition += '    KSwordDebuggerCall\n    KSwordTitanInitialize\n    KSwordTitanControl\n'
(root / 'TitanEngine.def').write_text(definition)
print(f'Generated {len(decls)} canonical typed dispatch entries; {len(decls)-len(custom)} pure wrappers')
