// Generated by generate_forwarders.py. Canonical types are never retyped.
#pragma once
#pragma warning(push)
#pragma warning(disable: 4324)
#include "../third_party/x64dbg_abi/TitanEngine.h"
#pragma warning(pop)
namespace ksword::titan {
struct NativeApi {
    decltype(&::MemoryReadSafe) MemoryReadSafe = nullptr;
    decltype(&::MemoryReadUnsafe) MemoryReadUnsafe = nullptr;
    decltype(&::MemoryWriteSafe) MemoryWriteSafe = nullptr;
    decltype(&::MemoryQuerySafe) MemoryQuerySafe = nullptr;
    decltype(&::MemoryAllocSafe) MemoryAllocSafe = nullptr;
    decltype(&::MemoryFreeSafe) MemoryFreeSafe = nullptr;
    decltype(&::MemoryProtectSafe) MemoryProtectSafe = nullptr;
    decltype(&::GetPEBLocation) GetPEBLocation = nullptr;
    decltype(&::GetTEBLocation) GetTEBLocation = nullptr;
    decltype(&::InitDebugW) InitDebugW = nullptr;
    decltype(&::InitReplayW) InitReplayW = nullptr;
    decltype(&::GetSessionInfo) GetSessionInfo = nullptr;
    decltype(&::ReplayGetPosition) ReplayGetPosition = nullptr;
    decltype(&::ReplayGetExtent) ReplayGetExtent = nullptr;
    decltype(&::ReplaySetPosition) ReplaySetPosition = nullptr;
    decltype(&::ReplayRunBack) ReplayRunBack = nullptr;
    decltype(&::ReplayStepBack) ReplayStepBack = nullptr;
    decltype(&::StopDebug) StopDebug = nullptr;
    decltype(&::SetBPXOptions) SetBPXOptions = nullptr;
    decltype(&::IsBPXEnabled) IsBPXEnabled = nullptr;
    decltype(&::SetBPX) SetBPX = nullptr;
    decltype(&::DeleteBPX) DeleteBPX = nullptr;
    decltype(&::SetMemoryBPXEx) SetMemoryBPXEx = nullptr;
    decltype(&::RemoveMemoryBPX) RemoveMemoryBPX = nullptr;
    decltype(&::GetFullContextDataEx) GetFullContextDataEx = nullptr;
    decltype(&::SetFullContextDataEx) SetFullContextDataEx = nullptr;
    decltype(&::GetContextDataEx) GetContextDataEx = nullptr;
    decltype(&::SetContextDataEx) SetContextDataEx = nullptr;
    decltype(&::GetAVXContext) GetAVXContext = nullptr;
    decltype(&::SetAVXContext) SetAVXContext = nullptr;
    decltype(&::GetAVX512Context) GetAVX512Context = nullptr;
    decltype(&::SetAVX512Context) SetAVX512Context = nullptr;
    decltype(&::GetDebugData) GetDebugData = nullptr;
    decltype(&::SetCustomHandler) SetCustomHandler = nullptr;
    decltype(&::StepInto) StepInto = nullptr;
    decltype(&::StepOver) StepOver = nullptr;
    decltype(&::GetUnusedHardwareBreakPointRegister) GetUnusedHardwareBreakPointRegister = nullptr;
    decltype(&::SetHardwareBreakPoint) SetHardwareBreakPoint = nullptr;
    decltype(&::DeleteHardwareBreakPoint) DeleteHardwareBreakPoint = nullptr;
    decltype(&::RemoveAllBreakPoints) RemoveAllBreakPoints = nullptr;
    decltype(&::DebugLoop) DebugLoop = nullptr;
    decltype(&::SetNextDbgContinueStatus) SetNextDbgContinueStatus = nullptr;
    decltype(&::AttachDebugger) AttachDebugger = nullptr;
    decltype(&::DetachDebuggerEx) DetachDebuggerEx = nullptr;
    decltype(&::IsFileBeingDebugged) IsFileBeingDebugged = nullptr;
    decltype(&::TitanOpenProcess) TitanOpenProcess = nullptr;
    decltype(&::TitanOpenThread) TitanOpenThread = nullptr;
    decltype(&::TitanGetProcessImagePathW) TitanGetProcessImagePathW = nullptr;
    decltype(&::TitanGetModulePathW) TitanGetModulePathW = nullptr;
    decltype(&::TitanCloseHandle) TitanCloseHandle = nullptr;
    decltype(&::ProcessIsWow64) ProcessIsWow64 = nullptr;
    decltype(&::TitanTerminateProcess) TitanTerminateProcess = nullptr;
    decltype(&::RequestPause) RequestPause = nullptr;
    decltype(&::TitanCreateRemoteThread) TitanCreateRemoteThread = nullptr;
    decltype(&::TitanSuspendThread) TitanSuspendThread = nullptr;
    decltype(&::TitanResumeThread) TitanResumeThread = nullptr;
    decltype(&::TitanTerminateThread) TitanTerminateThread = nullptr;
    decltype(&::TitanGetThreadId) TitanGetThreadId = nullptr;
    decltype(&::TitanGetThreadPriority) TitanGetThreadPriority = nullptr;
    decltype(&::TitanSetThreadPriority) TitanSetThreadPriority = nullptr;
    decltype(&::TitanGetThreadTimes) TitanGetThreadTimes = nullptr;
    decltype(&::TitanQueryThreadCycleTime) TitanQueryThreadCycleTime = nullptr;
    decltype(&::SetEngineVariable) SetEngineVariable = nullptr;
    decltype(&::EngineCheckStructAlignment) EngineCheckStructAlignment = nullptr;
};
extern NativeApi nativeApi;
DWORD ensureNative();
}
