#include "../Ksword5.1/Ksword5.1/UI/MemoryAssembly.Core.h"
#include <Zydis.h>

#include <cstdlib>
#include <iomanip>
#include <iostream>
#include <string>
#include <vector>

using ks::ui::detail::AssemblyError;
using ks::ui::detail::assembleIntel;

namespace
{
    unsigned checks = 0;
    void require(bool condition, const std::string& description)
    {
        ++checks;
        if (condition) return;
        std::cerr << "FAIL: " << description << '\n';
        std::exit(1);
    }

    std::vector<std::uint8_t> assemble(const std::string& source,
        std::uint64_t address = 0x7FF600001000, bool x64 = true)
    {
        const auto result = assembleIntel(source, address, x64);
        require(result.success, source + " error=" + std::to_string(static_cast<int>(result.error))
            + " line=" + std::to_string(result.errorLine) + " " + result.detail);
        require(!result.bytes.empty(), "successful output is nonempty");
        return result.bytes;
    }

    ZydisDisassembledInstruction decode(const std::vector<std::uint8_t>& bytes,
        std::uint64_t address = 0x7FF600001000, bool x64 = true)
    {
        ZydisDisassembledInstruction decoded{};
        require(ZYAN_SUCCESS(ZydisDisassembleIntel(x64 ? ZYDIS_MACHINE_MODE_LONG_64
            : ZYDIS_MACHINE_MODE_LEGACY_32, address, bytes.data(), bytes.size(), &decoded)), "decode generated bytes");
        return decoded;
    }

    std::uint64_t target(const ZydisDisassembledInstruction& decoded,
        std::uint64_t address, unsigned operand = 0)
    {
        ZyanU64 result = 0;
        require(ZYAN_SUCCESS(ZydisCalcAbsoluteAddress(&decoded.info,
            &decoded.operands[operand], address, &result)), "resolve decoded target");
        if (decoded.info.machine_mode == ZYDIS_MACHINE_MODE_LEGACY_32)
            result &= UINT32_MAX;
        return result;
    }

    void rejected(const std::string& source, AssemblyError error, int line = 1)
    {
        const auto result = assembleIntel(source, 0x7FF600001000, true);
        require(!result.success && result.bytes.empty(), "reject without partial bytes: " + source);
        require(result.error == error && result.errorLine == line,
            "precise error: " + source + " actual=" + std::to_string(static_cast<int>(result.error)));
    }
}

int main()
{
    constexpr std::uint64_t va = 0x7FF600001000;
    require(assemble("mov rax,0x1122334455667788")
        == std::vector<std::uint8_t>({0x48,0xB8,0x88,0x77,0x66,0x55,0x44,0x33,0x22,0x11}), "mov imm64");
    require(assemble("mov eax,10") == assemble("mov eax,0x10"), "CE default hex");
    require(assemble("mov eax,0d16") == assemble("mov eax,10h"), "explicit decimal and suffix hex");
    require(assemble("mov al,-1") == std::vector<std::uint8_t>({0xB0,0xFF}), "negative immediate");
    assemble("sub rsp,28\nmov [rsp+20],rbx\nlea rdx,[rsi+rcx*4-20]\nret");
    assemble("movss xmm0,dword ptr [rcx+4]");
    assemble("movzx eax,byte ptr [rcx]");
    require(assemble("cmovae eax,ecx") == assemble("cmovnb eax,ecx"), "conditional move alias");
    require(assemble("setg al") == assemble("setnle al"), "set condition alias");
    require(assemble("lea rax,[rax+rsp]") == assemble("lea rax,[rsp+rax]"), "commutative unscaled stack base");
    assemble("rep movsb");
    assemble("lock inc dword ptr [rax]");
    assemble("mov eax,dword ptr fs:[30]", 0x401000, false);
    const auto gs = decode(assemble("mov rax,qword ptr gs:[60]"));
    require(gs.operands[1].mem.base == ZYDIS_REGISTER_NONE
        && gs.operands[1].mem.segment == ZYDIS_REGISTER_GS, "segment absolute address");
    const auto high32 = decode(assemble("mov eax,dword ptr [0xF0000010]", 0x401000, false), 0x401000, false);
    require(target(high32, 0x401000, 1) == 0xF0000010, "x86 high absolute memory VA");
    const auto rip = decode(assemble("mov rax,qword ptr [rip-20]"));
    require(target(rip, va, 1) == va + rip.info.length - 0x20, "raw RIP displacement");
    const auto absolute = decode(assemble("mov rax,qword ptr [0x7FF600004567]"));
    require(target(absolute, va, 1) == 0x7FF600004567, "x64 absolute displayed memory becomes RIP target");
    const auto relative = decode(assemble("lea rax,[rel 0x7FF600004567]"));
    require(target(relative, va, 1) == 0x7FF600004567, "explicit rel VA");
    const auto explicitAbsolute = decode(assemble("mov rax,qword ptr [abs 0xF0000010]"));
    require(explicitAbsolute.operands[1].mem.base == ZYDIS_REGISTER_NONE
        && target(explicitAbsolute, va, 1) == 0xF0000010, "explicit low 32-bit absolute VA in x64");
    const auto kernel = decode(assemble("mov eax,dword ptr [0xFFFFF80000103000]", 0xFFFFF80000100000),
        0xFFFFF80000100000);
    require(target(kernel, 0xFFFFF80000100000, 1) == 0xFFFFF80000103000, "kernel RIP VA");
    require(assemble("call [eax]", 0x401000, false) == assemble("call dword ptr [eax]", 0x401000, false),
        "x86 indirect near transfer implicit width");
    const auto branch = decode(assemble("jne 0x7FF600001040"));
    require(target(branch, va) == 0x7FF600001040, "absolute conditional branch target");
    const auto branch32 = decode(assemble("jmp 0xF0000010", 0x401000, false), 0x401000, false);
    require(target(branch32, 0x401000) == 0xF0000010, "x86 branch wraps rel32 in 32-bit address space");
    assemble("nop\njmp short 0x7FF600001082");
    require(assemble("je 0x7FF600001040") == assemble("jz 0x7FF600001040"), "conditional alias");
    // Exercise Zydis formatter text copied directly by the unified editor.
    for (const auto& source : {"mov rax,qword ptr [0x7FF600004567]", "jne 0x7FF600001040",
        "movss xmm0,dword ptr [rcx+4]", "lea rdx,[rsi+rcx*4-20]", "mov eax,dword ptr gs:[60]",
        "call qword ptr [rax]", "jmp qword ptr [rip+20]", "push qword ptr [rax]", "pop qword ptr [rax]"})
    {
        const auto original = decode(assemble(source));
        const auto roundTrip = decode(assemble(original.text));
        require(original.info.mnemonic == roundTrip.info.mnemonic, "formatter mnemonic round trip");
        require(std::string(original.text) == roundTrip.text, "formatter semantic round trip");
    }
    const auto labelled = assemble("; multi-line labels\nstart: nop\njz end\ndec ecx\njmp start\nend: ret");
    std::size_t offset = 0;
    std::uint64_t conditionalTarget = 0;
    while (offset < labelled.size())
    {
        const std::vector<std::uint8_t> rest(labelled.begin() + offset, labelled.end());
        const auto instruction = decode(rest, va + offset);
        if (instruction.info.mnemonic == ZYDIS_MNEMONIC_JZ)
            conditionalTarget = target(instruction, va + offset);
        if (instruction.info.mnemonic == ZYDIS_MNEMONIC_JMP)
            require(target(instruction, va + offset) == va, "backward local label");
        offset += instruction.info.length;
    }
    require(conditionalTarget == va + labelled.size() - 1, "forward local label");
    assemble("dead: nop\njmp dead");
    rejected("nop\nunknown_instruction eax", AssemblyError::UnknownMnemonic, 2);
    rejected("jmp missing_label", AssemblyError::UnknownLabel);
    rejected("mov [rax],1", AssemblyError::AmbiguousMemorySize);
    rejected("movzx eax,[rax]", AssemblyError::AmbiguousMemorySize);
    rejected("mov al,1ff", AssemblyError::InvalidInstruction);
    rejected("mov eax,100000000", AssemblyError::InvalidInstruction);
    rejected("add rax,ffffffff", AssemblyError::InvalidInstruction);
    rejected("mov eax,10000000000000000", AssemblyError::InvalidNumber);
    rejected("mov eax,[rax++1]", AssemblyError::InvalidOperands);
    rejected("mov eax,[rax+rcx*3]", AssemblyError::InvalidMemory);
    rejected("mov eax,[rip+rax]", AssemblyError::InvalidMemory);
    rejected("mov eax,[rip+80000000]", AssemblyError::InvalidMemory);
    rejected("label: nop\nlabel: ret", AssemblyError::DuplicateLabel, 2);
    rejected("jmp 0x0000000010000000", AssemblyError::InvalidInstruction);
    rejected("; comments only", AssemblyError::EmptySource, 0);
    require(!assembleIntel("mov rax,rbx", 0x401000, false).success, "x86 rejects 64-bit register");
    require(!assembleIntel("nop\nnop", UINT64_MAX, true).success, "reject address overflow");
    require(!assembleIntel(std::string(65537, ' '), va, true).success, "source bound");
    std::cout << "PASS: " << checks << " memory assembly checks\n";
}
